{% set name = "nbgitpuller-link" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ca5393857a86ceb27ca4ed16dd73875d978abfb44f714dfd43463d9e0b30f926

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - nbgitpuller-link=nbgitpuller_link.cli:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - validators

test:
  imports:
    - nbgitpuller_link
  requires:
    - pip
  commands:
    - pip check
    - nbgitpuller-link --version
    - nbgitpuller-link --help

about:
  home: https://github.com/mdpiper/nbgitpuller-link
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: |
    Generate an nbgitpuller link through a command-line interface or Python code
  description: |
    Use nbgitpuller-link to create an URL used by nbgitpuller
    <https://jupyterhub.github.io/nbgitpuller> to provision files from a git
    repository on a JupyterHub. nbgitpuller-link has a handy, scriptable CLI
    and a Python API.

extra:
  recipe-maintainers:
    - mdpiper
